# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pygments latex2mathml beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Clean /docs
      run: |
        rm -f docs/*.html docs/*.css
    - name: Build HTML pages
      run: |
        python src/converter.py
    - name: Commit files
      run: |
        git config --local user.name "07734willy"
        git add -f ./docs
        git commit -m "Updating the repository GitHub html pages in the docs folder"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
